module.exports = {
  apps: [
    {
      name: 'api_gateway',
      cwd: './backend/api_gateway',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3001 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'billing_service',
      cwd: './backend/billing_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3004 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'crm_service',
      cwd: './backend/crm_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3005 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'employee_service',
      cwd: './backend/employee_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3002 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'ven_inv_service',
      cwd: './backend/ven_inv_service',
      script: 'node',
      args: 'dist/app.js',
      env: { PORT: 3003 },
      autorestart: true,
      watch: false,
    },
    {
      name: 'frontend',
      cwd: './frontend',
      // Use the next binary directly – avoids spawning a shell/pnpm wrapper
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      env: { PORT: 3000 },
      autorestart: true,
      watch: false,
    },
  ],
};
