export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  APPROVED = 'APPROVED', // @deprecated - use EMPLOYEE_APPROVED or FINANCE_APPROVED
  EMPLOYEE_APPROVED = 'EMPLOYEE_APPROVED',
  FINANCE_APPROVED = 'FINANCE_APPROVED',
  ACTIVE_LEASE = 'ACTIVE_LEASE',
  REJECTED = 'REJECTED',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}
